# Generated by Django 5.0.1 on 2024-06-27 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 27, 18, 41, 46, 690907, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
